import * as cp from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

const INSTALL = path.resolve(__dirname, "..", "scripts", "install.sh");
const TEMPLATE = path.resolve(__dirname, "..", "templates", "robin.yml");

describe("curl installer", () => {
  let dir: string;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "robin-install-"));
    cp.execSync("git init -q", { cwd: dir });
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const run = (env: Record<string, string> = {}) =>
    cp.execFileSync("bash", [INSTALL], {
      cwd: dir,
      env: { ...process.env, ROBIN_SKILL: "0", ...env },
      stdio: "pipe",
    }).toString();

  it("archives a historical workflow and creates the canonical workflow", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    fs.writeFileSync(
      path.join(workflows, "code-review.yml"),
      "name: Universal Code Reviewer\njobs:\n  review:\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\n",
    );
    fs.writeFileSync(
      path.join(workflows, "old-robin.yaml"),
      "name: Robin\njobs:\n  review:\n    steps:\n      - uses: antongulin/robin@v1\n",
    );

    const output = run();
    const canonical = fs.readFileSync(path.join(workflows, "robin.yml"), "utf8");

    expect(canonical).toBe(fs.readFileSync(TEMPLATE, "utf8"));
    expect(output).toContain("Multiple Robin workflows found; using default ref (main)");
    expect(output).toContain("Archived .github/workflows/code-review.yml");
    expect(canonical).toContain("Generated by robin-review");
    expect(canonical).toContain("actions: read");
    expect(canonical).toContain("antongulin/robin/.github/workflows/review.yml@main");
    expect(
      fs.existsSync(
        path.join(dir, ".github", "robin-workflow-archive", "code-review.yml.disabled"),
      ),
    ).toBe(true);
    expect(
      fs.existsSync(path.join(dir, ".github", "robin-workflow-archive", "old-robin.yaml.disabled")),
    ).toBe(true);

    fs.copyFileSync(
      path.join(dir, ".github", "robin-workflow-archive", "code-review.yml.disabled"),
      path.join(workflows, "code-review.yml"),
    );
    const duplicateOutput = run();
    expect(duplicateOutput).toContain(
      "Removed .github/workflows/code-review.yml (identical copy already at .github/robin-workflow-archive/code-review.yml.disabled)",
    );
  });

  it("no longer subscribes the consumer workflow to synchronize", () => {
    run();

    const canonical = fs.readFileSync(path.join(dir, ".github", "workflows", "robin.yml"), "utf8");
    expect(canonical).toContain("types: [opened, reopened, ready_for_review]");
    expect(canonical).not.toContain("synchronize");
    expect(canonical).toContain("issue_comment");
  });

  it("recognises the suelio-arts fork as a Robin workflow", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    fs.writeFileSync(
      path.join(workflows, "fork-review.yml"),
      "name: Robin\njobs:\n  review:\n    steps:\n      - uses: suelio-arts/robin@f6ab938\n",
    );

    run();

    expect(fs.existsSync(path.join(workflows, "fork-review.yml"))).toBe(false);
    expect(
      fs.existsSync(path.join(dir, ".github", "robin-workflow-archive", "fork-review.yml.disabled")),
    ).toBe(true);
  });

  it("is idempotent after migration", () => {
    run({ ROBIN_REF: "v1" });

    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    const lfWorkflow = fs.readFileSync(workflowPath, "utf8");
    fs.writeFileSync(workflowPath, lfWorkflow.replace(/\n/g, "\r\n"));

    const output = run();
    const canonical = fs.readFileSync(workflowPath, "utf8");

    expect(output).toContain("is already current");
    expect(canonical).toContain("review.yml@v1");
    expect(canonical).toContain("\r\n");
    expect(fs.existsSync(path.join(dir, ".github", "robin-workflow-archive"))).toBe(false);
  });

  it("uses a numbered archive when the first destination has different content", () => {
    const workflows = path.join(dir, ".github", "workflows");
    const archive = path.join(dir, ".github", "robin-workflow-archive");
    fs.mkdirSync(workflows, { recursive: true });
    fs.mkdirSync(archive, { recursive: true });
    const legacy =
      "name: Universal\r Code Reviewer\r\njobs:\r\n  review:\r\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\r\n";
    fs.writeFileSync(path.join(workflows, "code-review.yml"), legacy);
    fs.writeFileSync(
      path.join(archive, "code-review.yml.disabled"),
      legacy.replace("Universal\r Code", "Universal Code"),
    );

    run();

    expect(fs.readFileSync(path.join(archive, "code-review.yml.1.disabled"), "utf8")).toBe(
      legacy,
    );
  });

  it("refuses to overwrite an unrelated canonical workflow", () => {
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
    fs.writeFileSync(workflowPath, "name: Unrelated automation\n");

    expect(() => run()).toThrow();
    expect(fs.readFileSync(workflowPath, "utf8")).toBe("name: Unrelated automation\n");
  });

  it("does not add a consumer workflow to Robin's source repository", () => {
    fs.writeFileSync(path.join(dir, "package.json"), '{"name":"robin-review"}\n');
    fs.writeFileSync(path.join(dir, "action.yml"), "name: Robin\n");
    fs.mkdirSync(path.join(dir, "skills", "robin"), { recursive: true });
    fs.writeFileSync(path.join(dir, "skills", "robin", "SKILL.md"), "# Robin\n");
    fs.mkdirSync(path.join(dir, ".github", "workflows"), { recursive: true });
    fs.writeFileSync(path.join(dir, ".github", "workflows", "self-test.yml"), "name: Self-Test\n");

    const output = run();

    expect(output).toContain("Robin source repository detected");
    expect(fs.existsSync(path.join(dir, ".github", "workflows", "robin.yml"))).toBe(false);
  });

  it("preserves a modern ref while migrating an older canonical workflow", () => {
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
    fs.writeFileSync(
      workflowPath,
      "name: Robin\njobs:\n  review:\n    uses: antongulin/robin/.github/workflows/review.yml@v1\n",
    );

    run();

    expect(fs.readFileSync(workflowPath, "utf8")).toContain("review.yml@v1");
    expect(
      fs.existsSync(path.join(dir, ".github", "robin-workflow-archive", "robin.yml.disabled")),
    ).toBe(true);
  });
});
