import * as cp from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

const BIN = path.resolve(__dirname, "..", "bin", "robin-review.js");
const TEMPLATE = path.resolve(__dirname, "..", "templates", "robin.yml");

// Each polling snapshot spawns a handful of fake `gh` processes; the wait-based
// fixtures need more than jest's 5 s default even though every sleep is 100 ms.
jest.setTimeout(30000);

describe("robin-review CLI", () => {
  let dir: string;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "robin-bin-"));
    cp.execSync("git init -q", { cwd: dir });
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const run = (env: Record<string, string> = {}) =>
    cp.execSync(`node "${BIN}"`, {
      stdio: "pipe",
      cwd: dir,
      env: { ...process.env, ROBIN_SKILL: "0", ...env },
    }).toString();

  it("creates the canonical workflow with the given ref", () => {
    run({ ROBIN_REF: "v2" });

    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    const workflow = fs.readFileSync(workflowPath, "utf8");
    const expected = fs.readFileSync(TEMPLATE, "utf8").replace("review.yml@main", "review.yml@v2");
    expect(workflow).toBe(expected);
    expect(workflow).toContain("Generated by robin-review");
    expect(workflow).toContain("uses: antongulin/robin/.github/workflows/review.yml@v2");
    expect(workflow).toContain("LLM_API_KEY: ${{ secrets.LLM_API_KEY }}");
  });

  it("no longer reviews every synchronized head", () => {
    run({ ROBIN_REF: "v2" });

    const workflow = fs.readFileSync(path.join(dir, ".github", "workflows", "robin.yml"), "utf8");
    expect(workflow).toContain("types: [opened, reopened, ready_for_review]");
    expect(workflow).not.toContain("synchronize");
    expect(workflow).toContain("issue_comment");
  });

  it("is idempotent and keeps an existing modern ref", () => {
    run({ ROBIN_REF: "v1" });
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    const before = fs.readFileSync(workflowPath, "utf8");

    const output = run();

    expect(output).toContain("is already current");
    expect(fs.readFileSync(workflowPath, "utf8")).toBe(before);
    expect(fs.existsSync(path.join(dir, ".github", "robin-workflow-archive"))).toBe(false);
  });

  it("archives historical workflow names and variants before creating the canonical file", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    fs.writeFileSync(
      path.join(workflows, "code-review.yml"),
      "name: Universal Code Reviewer\njobs:\n  review:\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\n",
    );
    fs.writeFileSync(
      path.join(workflows, "ai-review.yaml"),
      "name: Robin\njobs:\n  review:\n    steps:\n      - uses: antongulin/robin@main\n",
    );
    fs.writeFileSync(
      path.join(workflows, "legacy-action.yml"),
      "name: Code Review\njobs:\n  review:\n    steps:\n      - uses: antongulin/universal-code-reviewer@main\n",
    );

    const output = run();
    const archive = path.join(dir, ".github", "robin-workflow-archive");
    const canonical = fs.readFileSync(path.join(workflows, "robin.yml"), "utf8");

    expect(output).toContain("Multiple Robin workflows found; using default ref (main)");
    expect(output).toContain("Archived .github/workflows/code-review.yml");
    expect(output).toContain("Archived .github/workflows/ai-review.yaml");
    expect(output).toContain("Archived .github/workflows/legacy-action.yml");
    expect(fs.existsSync(path.join(workflows, "code-review.yml"))).toBe(false);
    expect(fs.existsSync(path.join(workflows, "ai-review.yaml"))).toBe(false);
    expect(fs.existsSync(path.join(workflows, "legacy-action.yml"))).toBe(false);
    expect(fs.existsSync(path.join(archive, "code-review.yml.disabled"))).toBe(true);
    expect(fs.existsSync(path.join(archive, "ai-review.yaml.disabled"))).toBe(true);
    expect(fs.existsSync(path.join(archive, "legacy-action.yml.disabled"))).toBe(true);
    expect(canonical).toContain("antongulin/robin/.github/workflows/review.yml@main");

    fs.copyFileSync(
      path.join(archive, "code-review.yml.disabled"),
      path.join(workflows, "code-review.yml"),
    );
    const duplicateOutput = run();
    expect(duplicateOutput).toContain(
      "Removed .github/workflows/code-review.yml (identical copy already at .github/robin-workflow-archive/code-review.yml.disabled)",
    );
  });

  it("recognises the suelio-arts fork as a Robin workflow", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    fs.writeFileSync(
      path.join(workflows, "fork-review.yml"),
      "name: Robin\njobs:\n  review:\n    steps:\n      - uses: suelio-arts/robin@f6ab938\n",
    );

    run();

    expect(fs.existsSync(path.join(workflows, "fork-review.yml"))).toBe(false);
    expect(
      fs.existsSync(path.join(dir, ".github", "robin-workflow-archive", "fork-review.yml.disabled")),
    ).toBe(true);
  });

  it("preserves a fork's direct-action pin when migrating it to the reusable form", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    fs.writeFileSync(
      path.join(workflows, "fork-review.yml"),
      "name: Robin\njobs:\n  review:\n    steps:\n      - uses: suelio-arts/robin@f6ab9388c57d9c907c1fd87e413f31c8c53c2f0a\n",
    );

    run();

    const canonical = fs.readFileSync(path.join(workflows, "robin.yml"), "utf8");
    expect(canonical).toContain(
      "uses: suelio-arts/robin/.github/workflows/review.yml@f6ab9388c57d9c907c1fd87e413f31c8c53c2f0a",
    );
    expect(canonical).not.toContain("antongulin/robin");
    expect(
      fs.existsSync(path.join(dir, ".github", "robin-workflow-archive", "fork-review.yml.disabled")),
    ).toBe(true);
  });

  it("requires a complete ref before treating a reference as Robin", () => {
    const { isRobinWorkflow } = require("../bin/robin-workflow-ref");
    const step = (reference: string) =>
      `name: Robin\njobs:\n  review:\n    steps:\n      - uses: ${reference}\n`;

    expect(isRobinWorkflow(step("antongulin/robin@"))).toBe(false);
    expect(isRobinWorkflow(step("antongulin/robin@main@invalid"))).toBe(false);
    expect(isRobinWorkflow(step("suelio-arts/robin@f6ab9388c57d9c907c1fd87e413f31c8c53c2f0a"))).toBe(true);
    expect(
      isRobinWorkflow("name: Robin\njobs:\n  review:\n    uses: antongulin/robin/.github/workflows/review.yml@v1\n"),
    ).toBe(true);
  });

  it("leaves a workflow with a malformed Robin reference alone", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    const malformed = "name: Robin\njobs:\n  review:\n    steps:\n      - uses: antongulin/robin@\n";
    fs.writeFileSync(path.join(workflows, "broken.yml"), malformed);

    run();

    expect(fs.readFileSync(path.join(workflows, "broken.yml"), "utf8")).toBe(malformed);
    expect(fs.existsSync(path.join(dir, ".github", "robin-workflow-archive"))).toBe(false);
  });

  it("does not carry a legacy universal-code-reviewer reference forward as a pin", () => {
    const { robinWorkflowPin } = require("../bin/robin-workflow-ref");

    expect(
      robinWorkflowPin("jobs:\n  review:\n    steps:\n      - uses: antongulin/universal-code-reviewer@v0\n"),
    ).toBeNull();
    expect(
      robinWorkflowPin("jobs:\n  review:\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v1\n"),
    ).toBeNull();
    expect(
      robinWorkflowPin("jobs:\n  review:\n    steps:\n      - uses: suelio-arts/robin@f6ab938\n"),
    ).toEqual({ owner: "suelio-arts", ref: "f6ab938" });
  });

  it("preserves a fork pin's owner and ref", () => {
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
    fs.writeFileSync(
      workflowPath,
      "name: Robin\njobs:\n  review:\n    uses: suelio-arts/robin/.github/workflows/review.yml@f6ab938\n",
    );

    run();

    const canonical = fs.readFileSync(workflowPath, "utf8");
    expect(canonical).toContain("uses: suelio-arts/robin/.github/workflows/review.yml@f6ab938");
    expect(canonical).not.toContain("antongulin/robin/.github/workflows/review.yml");
    expect(canonical).toContain("Generated by robin-review");
  });

  it("ignores a Robin uses: line quoted inside a run block", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    const documentation = [
      "name: Docs",
      "on: push",
      "jobs:",
      "  explain:",
      "    steps:",
      "      - run: |",
      "          cat <<'SNIPPET'",
      "          jobs:",
      "            review:",
      "              uses: antongulin/robin/.github/workflows/review.yml@main",
      "          SNIPPET",
      "",
    ].join("\n");
    fs.writeFileSync(path.join(workflows, "docs.yml"), documentation);

    run();

    expect(fs.readFileSync(path.join(workflows, "docs.yml"), "utf8")).toBe(documentation);
    expect(fs.existsSync(path.join(dir, ".github", "robin-workflow-archive"))).toBe(false);
  });

  it("archives an older canonical workflow while preserving its modern ref", () => {
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
    fs.writeFileSync(
      workflowPath,
      "name: Robin\njobs:\n  review:\n    uses: antongulin/robin/.github/workflows/review.yml@v1\n",
    );

    run();

    expect(fs.readFileSync(workflowPath, "utf8")).toContain("review.yml@v1");
    expect(
      fs.existsSync(path.join(dir, ".github", "robin-workflow-archive", "robin.yml.disabled")),
    ).toBe(true);
  });

  it("uses a numbered archive when the first destination has different content", () => {
    const workflows = path.join(dir, ".github", "workflows");
    const archive = path.join(dir, ".github", "robin-workflow-archive");
    fs.mkdirSync(workflows, { recursive: true });
    fs.mkdirSync(archive, { recursive: true });
    const legacy =
      "name: Universal Code Reviewer\njobs:\n  review:\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\n";
    fs.writeFileSync(path.join(workflows, "code-review.yml"), legacy);
    fs.writeFileSync(path.join(archive, "code-review.yml.disabled"), "different archive\n");

    run();

    expect(fs.readFileSync(path.join(archive, "code-review.yml.1.disabled"), "utf8")).toBe(
      legacy,
    );
  });

  it("refuses to overwrite an unrelated canonical workflow", () => {
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
    fs.writeFileSync(workflowPath, "name: Unrelated automation\n");

    expect(() => run()).toThrow();
    expect(fs.readFileSync(workflowPath, "utf8")).toBe("name: Unrelated automation\n");
  });

  it("does not add a consumer workflow to Robin's source repository", () => {
    fs.writeFileSync(path.join(dir, "package.json"), '{"name":"robin-review"}\n');
    fs.writeFileSync(path.join(dir, "action.yml"), "name: Robin\n");
    fs.mkdirSync(path.join(dir, "skills", "robin"), { recursive: true });
    fs.writeFileSync(path.join(dir, "skills", "robin", "SKILL.md"), "# Robin\n");
    fs.mkdirSync(path.join(dir, ".github", "workflows"), { recursive: true });
    fs.writeFileSync(path.join(dir, ".github", "workflows", "self-test.yml"), "name: Self-Test\n");

    const output = run();

    expect(output).toContain("Robin source repository detected");
    expect(fs.existsSync(path.join(dir, ".github", "workflows", "robin.yml"))).toBe(false);
  });

  it("rejects a ROBIN_REF with YAML metacharacters", () => {
    expect(() => run({ ROBIN_REF: "main\njobs: {}" })).toThrow();
    expect(fs.existsSync(path.join(dir, ".github", "workflows", "robin.yml"))).toBe(false);
  });

  it("fails outside a git repository", () => {
    const bare = fs.mkdtempSync(path.join(os.tmpdir(), "robin-nogit-"));
    try {
      expect(() =>
        cp.execSync(`node "${BIN}"`, {
          cwd: bare,
          env: { ...process.env, ROBIN_SKILL: "0" },
          stdio: "pipe",
        })
      ).toThrow();
    } finally {
      fs.rmSync(bare, { recursive: true, force: true });
    }
  });

  it("is tracked as an executable npm binary", () => {
    expect(fs.statSync(BIN).mode & 0o111).not.toBe(0);
  });

  it("exposes exact-head PR review control", () => {
    const output = cp.execFileSync("node", [BIN, "pr", "--help"], { encoding: "utf8" });
    expect(output).toContain("robin-review pr [number|url]");
    expect(output).toContain("--rerun");
    expect(output).toContain("--json");
    expect(output).toContain("--local");
    expect(output).not.toContain("synchronize");
  });
});

// --------------------------------------------------------------------------
// `robin-review pr` — driven end to end through a fake `gh` on PATH and, for
// --local, a fake engine. Nothing here touches the network.
// --------------------------------------------------------------------------

const HEAD = "a1b2c3d4e5f60718293a4b5c6d7e8f9012345678";
const OLD_HEAD = "b1b2c3d4e5f60718293a4b5c6d7e8f9012345678";
const NEW_HEAD = "c1b2c3d4e5f60718293a4b5c6d7e8f9012345678";
/** What an issue_comment or workflow_dispatch run reports as its head: the default branch. */
const DEFAULT_HEAD = "d1b2c3d4e5f60718293a4b5c6d7e8f9012345678";
const WORKFLOW_ID = 326461432;
const ROBIN_PATH = ".github/workflows/robin.yml";
const SIGNATURE = ":bow_and_arrow: Robin";

/** A pull_request run: head_sha is the PR head and the API names the PR. */
const prRun = (over: Record<string, any> = {}) => ({
  id: 9,
  path: ROBIN_PATH,
  workflow_id: WORKFLOW_ID,
  event: "pull_request",
  head_branch: "feature",
  head_sha: HEAD,
  pull_requests: [{ number: 7, head: { sha: HEAD } }],
  status: "completed",
  conclusion: "success",
  created_at: "2026-01-01T00:00:00Z",
  html_url: "https://example/run/9",
  actor: { login: "octo-human" },
  ...over,
});

/** An issue_comment run: default-branch head, empty pull_requests — the API cannot tie it to a PR. */
const commentRun = (over: Record<string, any> = {}) => ({
  id: 21,
  path: ROBIN_PATH,
  workflow_id: WORKFLOW_ID,
  event: "issue_comment",
  head_branch: "main",
  head_sha: DEFAULT_HEAD,
  pull_requests: [],
  status: "in_progress",
  conclusion: null,
  created_at: new Date().toISOString(),
  display_title: "Some pull request title",
  html_url: "https://example/run/21",
  actor: { login: "octo-human" },
  ...over,
});

const ROBIN_WORKFLOW = [
  "name: Robin",
  "on:",
  "  pull_request:",
  "    types: [opened, reopened, ready_for_review]",
  "  issue_comment:",
  "    types: [created]",
  "jobs:",
  "  review:",
  "    uses: antongulin/robin/.github/workflows/review.yml@main",
  "",
].join("\n");

const ROBIN_WORKFLOW_NO_COMMAND = [
  "name: Robin",
  "on:",
  "  pull_request:",
  "    types: [opened]",
  "jobs:",
  "  review:",
  "    uses: suelio-arts/robin/.github/workflows/review.yml@main",
  "",
].join("\n");

const UNRELATED_WORKFLOW = ["name: CI", "on: push", "jobs:", "  review:", "    steps:", "      - run: true", ""].join(
  "\n",
);

/** The same triggers written as a flow mapping, which line scanning mis-reads. */
const ROBIN_WORKFLOW_FLOW_ON = [
  "name: Robin",
  "on: { pull_request: { types: [opened] }, issue_comment: { types: [created] } }",
  "jobs:",
  "  review:",
  "    uses: antongulin/robin/.github/workflows/review.yml@main",
  "",
].join("\n");

const marker = (
  outcome: string,
  head: string,
  counts?: [number, number, number, number],
): string => {
  const tail = counts
    ? ` high=${counts[0]} medium=${counts[1]} low=${counts[2]} suggestions=${counts[3]}`
    : "";
  return `<!-- robin-outcome: v1 ${outcome} head=${head}${tail} -->`;
};

interface FakeReview {
  id: number;
  commit_id: string;
  state: string;
  body: string;
  submitted_at: string;
  html_url?: string;
  user?: { login: string };
}

const botReview = (overrides: Partial<FakeReview>): FakeReview => ({
  id: 1,
  commit_id: HEAD,
  state: "COMMENTED",
  body: "",
  submitted_at: "2026-01-01T00:00:00Z",
  html_url: "https://example/review/1",
  user: { login: "github-actions[bot]" },
  ...overrides,
});

interface Fixture {
  pr?: { number: number; headRefOid: string; baseRefName: string; baseRefOid: string; url: string };
  headSteps?: string[];
  reviews?: FakeReview[];
  reviewsSteps?: FakeReview[][];
  runs?: any[];
  runsSteps?: any[][];
  workflows?: { id: number; path: string; state: string }[];
  contents?: Record<string, string>;
  login?: string;
  token?: string;
  reviewsById?: Record<string, any>;
}

/**
 * A `gh` stand-in that answers exactly the calls the CLI makes, logs every
 * invocation so tests can assert that no comment was posted, and can advance
 * through per-call phases so an "active run then finished run" can be replayed.
 */
const FAKE_GH = `#!/usr/bin/env node
const fs = require("fs");
const fixture = JSON.parse(fs.readFileSync(process.env.FAKE_GH_FIXTURE, "utf8"));
const statePath = process.env.FAKE_GH_LOG + ".state.json";
const args = process.argv.slice(2);
fs.appendFileSync(process.env.FAKE_GH_LOG, args.join(" ") + "\\n");

const state = fs.existsSync(statePath) ? JSON.parse(fs.readFileSync(statePath, "utf8")) : {};
const bump = (name) => {
  const index = state[name] || 0;
  state[name] = index + 1;
  fs.writeFileSync(statePath, JSON.stringify(state));
  return index;
};
const phase = (name, index) => {
  const steps = fixture[name + "Steps"];
  if (steps) return steps[Math.min(index, steps.length - 1)];
  return fixture[name] || [];
};
const out = (value) => {
  process.stdout.write(typeof value === "string" ? value : JSON.stringify(value));
  process.exit(0);
};
const joined = args.join(" ");

if (joined === "auth token") out(fixture.token || "fake-token");
if (joined === "api user --jq .login") out(fixture.login || "octo-human");
if (args[0] === "repo" && args[1] === "view") out(process.env.FAKE_GH_REPO || "o/r");
if (args[0] === "pr" && args[1] === "view") {
  const fields = args[args.indexOf("--json") + 1];
  if (fields === "headRefOid") {
    const heads = fixture.headSteps || [fixture.pr.headRefOid];
    const index = bump("head");
    out({ headRefOid: heads[Math.min(index, heads.length - 1)] });
  }
  out(fixture.pr);
}
if (args[0] === "pr" && args[1] === "comment") {
  bump("comment");
  out("");
}
const url = args.find((arg) => arg.startsWith("repos/")) || "";
if (url.includes("/pulls/") && url.includes("/reviews/")) {
  const id = url.split("/reviews/")[1];
  const review = (fixture.reviewsById || {})[id];
  if (!review) { process.stderr.write("not found\\n"); process.exit(1); }
  out(review);
}
if (url.includes("/reviews?")) out([phase("reviews", bump("reviews"))]);
if (url.includes("/actions/workflows/") && url.includes("/runs")) {
  // The CLI asks several bounded questions per snapshot; every one sees the same
  // phase, and the last of them (the head_sha query) advances to the next.
  const index = state.runs || 0;
  if (url.includes("head_sha=")) bump("runs");
  out({ workflow_runs: phase("runs", index) });
}
if (url.includes("/actions/workflows")) out([{ total_count: (fixture.workflows || []).length, workflows: fixture.workflows || [] }]);
if (url.includes("/contents/")) {
  const file = url.split("/contents/")[1].split("?")[0];
  const source = (fixture.contents || {})[file];
  if (source === undefined) { process.stderr.write("no content\\n"); process.exit(1); }
  out(Buffer.from(source, "utf8").toString("base64"));
}
process.stderr.write("unexpected gh args: " + joined + "\\n");
process.exit(1);
`;

describe("robin-review pr", () => {
  let dir: string;
  let logPath: string;
  let fixturePath: string;
  let env: NodeJS.ProcessEnv;

  const defaultFixture = (): Fixture => ({
    pr: { number: 7, headRefOid: HEAD, baseRefName: "main", baseRefOid: OLD_HEAD, url: "https://example/pr/7" },
    reviews: [],
    runs: [],
    workflows: [{ id: WORKFLOW_ID, path: ROBIN_PATH, state: "active" }],
    contents: { [ROBIN_PATH]: ROBIN_WORKFLOW },
    login: "octo-human",
  });

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "robin-pr-"));
    const binDir = path.join(dir, "bin");
    fs.mkdirSync(binDir);
    const fakeGh = path.join(binDir, "gh");
    fs.writeFileSync(fakeGh, FAKE_GH);
    fs.chmodSync(fakeGh, 0o755);
    logPath = path.join(dir, "gh.log");
    fs.writeFileSync(logPath, "");
    fixturePath = path.join(dir, "fixture.json");
    env = {
      ...process.env,
      PATH: `${binDir}:${process.env.PATH}`,
      FAKE_GH_LOG: logPath,
      FAKE_GH_FIXTURE: fixturePath,
    };
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const withFixture = (fixture: Fixture) => {
    fs.writeFileSync(fixturePath, JSON.stringify({ ...defaultFixture(), ...fixture }));
  };

  const pr = (args: string[] = [], extraEnv: NodeJS.ProcessEnv = {}) =>
    cp.spawnSync("node", [BIN, "pr", "7", "--repo", "o/r", "--json", "--interval", "0.1", ...args], {
      encoding: "utf8",
      env: { ...env, ...extraEnv },
    });

  const ghCalls = () => fs.readFileSync(logPath, "utf8").split("\n").filter(Boolean);
  const parse = (result: cp.SpawnSyncReturns<string>) => JSON.parse(result.stdout);

  it("reports clean for a COMMENTED review whose marker counts zero findings", () => {
    withFixture({
      reviews: [botReview({ body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [0, 0, 0, 0])}` })],
    });

    const result = pr();

    expect({ code: result.status, body: parse(result) }).toEqual({
      code: 0,
      body: expect.objectContaining({
        status: "clean",
        coverage: "reviewed",
        verdict: "COMMENTED",
        blocking: false,
        execution: "actions",
        findings: { high: 0, medium: 0, low: 0, suggestions: 0 },
      }),
    });
  });

  it("reports advisory findings without ever calling them blocked", () => {
    withFixture({
      reviews: [botReview({ body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [1, 0, 2, 0])}` })],
    });

    const result = pr();

    expect(result.status).toBe(2);
    expect(parse(result)).toEqual(
      expect.objectContaining({
        status: "findings",
        coverage: "reviewed",
        verdict: "COMMENTED",
        blocking: false,
        findings: { high: 1, medium: 0, low: 2, suggestions: 0 },
      }),
    );
  });

  it("marks a CHANGES_REQUESTED review as blocking", () => {
    withFixture({
      reviews: [
        botReview({
          state: "CHANGES_REQUESTED",
          body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [2, 0, 0, 0])}`,
        }),
      ],
    });

    const result = pr();

    expect(result.status).toBe(2);
    expect(parse(result)).toEqual(
      expect.objectContaining({ status: "findings", blocking: true, verdict: "CHANGES_REQUESTED" }),
    );
  });

  it("reports incomplete coverage when the engine failed at this head", () => {
    withFixture({
      reviews: [botReview({ body: `## ${SIGNATURE}\n${marker("incomplete", HEAD)}` })],
    });

    const result = pr();

    expect(result.status).toBe(3);
    expect(parse(result)).toEqual(
      expect.objectContaining({ status: "incomplete", coverage: "incomplete", findings: null }),
    );
    expect(parse(result).message).not.toContain("synchronize");
  });

  it("never lets an older complete receipt mask a newer incomplete one at the same head", () => {
    withFixture({
      reviews: [
        botReview({
          id: 1,
          submitted_at: "2026-01-01T00:00:00Z",
          body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [0, 0, 0, 0])}`,
        }),
        botReview({
          id: 2,
          submitted_at: "2026-01-01T01:00:00Z",
          body: `## ${SIGNATURE}\n${marker("incomplete", HEAD)}`,
        }),
      ],
    });

    const result = pr();

    expect(result.status).toBe(3);
    expect(parse(result)).toEqual(
      expect.objectContaining({ coverage: "incomplete", receipt: expect.objectContaining({ reviewId: 2 }) }),
    );
  });

  it("falls back to stat blocks for a pre-marker engine's review body", () => {
    withFixture({
      reviews: [
        botReview({
          body: `## ${SIGNATURE}\n\n:rotating_light: **1 High** | :bulb: **3 Suggestions**\n`,
        }),
      ],
    });

    const result = pr();

    expect(result.status).toBe(2);
    expect(parse(result)).toEqual(
      expect.objectContaining({
        coverage: "reviewed",
        findings: { high: 1, medium: 0, low: 0, suggestions: 3 },
      }),
    );
  });

  it("reads counts from the stat blocks when a reused marker carries none", () => {
    withFixture({
      reviews: [
        botReview({
          body: `## ${SIGNATURE}\n\n:white_check_mark: **No issues found**\n\n${marker("reused", HEAD)}`,
        }),
      ],
    });

    const result = pr();

    expect({ code: result.status, body: parse(result) }).toEqual({
      code: 0,
      body: expect.objectContaining({
        status: "clean",
        coverage: "reused",
        findings: { high: 0, medium: 0, low: 0, suggestions: 0 },
      }),
    });
  });

  it("never calls a review clean when its counts are unknown", () => {
    withFixture({
      reviews: [
        botReview({ body: `## ${SIGNATURE}\n${marker("reused", HEAD)}` }),
      ],
    });

    const result = pr();

    expect(result.status).toBe(2);
    const body = parse(result);
    expect(body).toEqual(expect.objectContaining({ status: "findings", coverage: "reused", findings: null }));
    expect(body.message).toContain("could not be read");
  });

  it("treats a skipped receipt as complete coverage with no findings", () => {
    withFixture({
      reviews: [botReview({ body: `## ${SIGNATURE}\n${marker("skipped", HEAD, [0, 0, 0, 0])}` })],
    });

    const result = pr();

    expect({ code: result.status, body: parse(result) }).toEqual({
      code: 0,
      body: expect.objectContaining({ status: "clean", coverage: "skipped" }),
    });
  });

  it("ignores a marker-less Robin-looking review from the authenticated login", () => {
    withFixture({
      reviews: [
        botReview({
          user: { login: "octo-human" },
          body: `Quoting the last run:\n\n## ${SIGNATURE}\n\n:rotating_light: **1 High**\n`,
        }),
      ],
    });

    const result = pr();

    expect(result.status).toBe(3);
    expect(parse(result)).toEqual(
      expect.objectContaining({ status: "missing", findings: null, receipt: null }),
    );
  });

  it("ignores a receipt from an untrusted author", () => {
    withFixture({
      reviews: [
        botReview({
          user: { login: "drive-by" },
          body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [0, 0, 0, 0])}`,
        }),
      ],
    });

    const result = pr();

    expect(result.status).toBe(3);
    expect(parse(result).coverage).toBe("missing");
  });

  it("reports outdated when only older heads carry receipts", () => {
    withFixture({
      reviews: [
        botReview({
          commit_id: OLD_HEAD,
          body: `## ${SIGNATURE}\n${marker("reviewed", OLD_HEAD, [0, 0, 0, 0])}`,
        }),
      ],
    });

    const result = pr();

    expect(result.status).toBe(3);
    expect(parse(result)).toEqual(expect.objectContaining({ status: "outdated", coverage: "outdated" }));
  });

  it("reports missing without suggesting synchronize, and never lists runs of unrelated workflows", () => {
    withFixture({
      workflows: [
        { id: WORKFLOW_ID, path: ROBIN_PATH, state: "active" },
        { id: 999, path: ".github/workflows/ci.yml", state: "active" },
      ],
      contents: { [ROBIN_PATH]: ROBIN_WORKFLOW, ".github/workflows/ci.yml": UNRELATED_WORKFLOW },
      runs: [],
    });

    const result = pr();

    expect(result.status).toBe(3);
    const body = parse(result);
    expect(body).toEqual(expect.objectContaining({ status: "missing", check: null }));
    expect(body.message).toContain("/robin");
    expect(body.message).not.toContain("synchronize");
    expect(ghCalls().some((call) => call.includes("actions/workflows/999/runs"))).toBe(false);
    expect(ghCalls().some((call) => call.includes(`actions/workflows/${WORKFLOW_ID}/runs`))).toBe(true);
  });

  it("calls a successful run that posted nothing missing, not incomplete", () => {
    withFixture({ runs: [prRun({ conclusion: "success" })] });

    const result = pr();

    expect(result.status).toBe(3);
    const body = parse(result);
    expect(body).toEqual(
      expect.objectContaining({
        status: "missing",
        coverage: "missing",
        check: { conclusion: "success", runUrl: "https://example/run/9", correlated: true, event: "pull_request" },
      }),
    );
    expect(body.message).toContain("the event was skipped or nothing was reviewed");
    expect(body.message).not.toContain("synchronize");
  });

  it("calls a failed run that posted nothing incomplete", () => {
    withFixture({ runs: [prRun({ conclusion: "failure" })] });

    const result = pr();

    expect(result.status).toBe(3);
    expect(parse(result)).toEqual(
      expect.objectContaining({ status: "incomplete", coverage: "incomplete" }),
    );
    expect(parse(result).message).toContain("finished as failure");
  });

  it("refuses to post /robin when the repository has no active Robin workflow", () => {
    withFixture({
      workflows: [{ id: 999, path: ".github/workflows/ci.yml", state: "active" }],
      contents: { ".github/workflows/ci.yml": UNRELATED_WORKFLOW },
    });

    const result = pr(["--rerun"]);

    expect(result.status).toBe(3);
    expect(parse(result).status).toBe("unavailable");
    expect(ghCalls().some((call) => call.startsWith("pr comment"))).toBe(false);
  });

  it("accepts a flow-mapping issue_comment trigger as a /robin command trigger", () => {
    withFixture({
      contents: { [ROBIN_PATH]: ROBIN_WORKFLOW_FLOW_ON },
      runsSteps: [[], [commentRun()], [commentRun({ status: "completed", conclusion: "success" })]],
      reviewsSteps: [
        [],
        [],
        [botReview({ body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [0, 0, 0, 0])}` })],
      ],
    });

    const result = pr(["--rerun", "--timeout", "20"]);

    expect(result.status).toBe(0);
    expect(parse(result).status).toBe("clean");
    expect(ghCalls().filter((call) => call.startsWith("pr comment"))).toEqual([
      "pr comment 7 --repo o/r --body /robin",
    ]);
  });

  it("refuses to post /robin when the Robin workflow has no issue_comment trigger", () => {
    withFixture({
      workflows: [{ id: WORKFLOW_ID, path: ROBIN_PATH, state: "active" }],
      contents: { [ROBIN_PATH]: ROBIN_WORKFLOW_NO_COMMAND },
    });

    const result = pr(["--rerun"]);

    expect(result.status).toBe(3);
    expect(parse(result)).toEqual(
      expect.objectContaining({ status: "unavailable", coverage: "unavailable" }),
    );
    expect(parse(result).message).toContain("issue_comment");
    expect(ghCalls().some((call) => call.startsWith("pr comment"))).toBe(false);
  });

  it("waits for an already active pull_request run instead of cancelling it with a new /robin", () => {
    const active = prRun({ status: "in_progress", conclusion: null });
    withFixture({
      runsSteps: [[active], [active], [prRun({ conclusion: "success" })]],
      reviewsSteps: [
        [],
        [],
        [botReview({ body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [0, 1, 0, 0])}` })],
      ],
    });

    const result = pr(["--rerun", "--timeout", "20"]);

    expect(result.status).toBe(2);
    expect(parse(result)).toEqual(
      expect.objectContaining({
        coverage: "reviewed",
        findings: { high: 0, medium: 1, low: 0, suggestions: 0 },
        check: { conclusion: "success", runUrl: "https://example/run/9", correlated: true, event: "pull_request" },
      }),
    );
    expect(ghCalls().some((call) => call.startsWith("pr comment"))).toBe(false);
  });

  it("waits for an active comment-triggered run the API cannot tie to this PR", () => {
    withFixture({
      runsSteps: [
        [commentRun()],
        [commentRun()],
        [commentRun({ status: "completed", conclusion: "success" })],
      ],
      reviewsSteps: [
        [],
        [],
        [botReview({ body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [0, 0, 0, 0])}` })],
      ],
    });

    const result = pr(["--rerun", "--timeout", "20"]);

    expect(result.status).toBe(0);
    expect(parse(result)).toEqual(expect.objectContaining({ status: "clean", coverage: "reviewed" }));
    expect(ghCalls().some((call) => call.startsWith("pr comment"))).toBe(false);
  });

  it("posts /robin once and follows the comment run it dispatched to a new receipt", () => {
    withFixture({
      runsSteps: [[], [commentRun()], [commentRun({ status: "completed", conclusion: "success" })]],
      reviewsSteps: [
        [],
        [],
        [botReview({ id: 5, body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [1, 0, 0, 0])}` })],
      ],
    });

    const result = pr(["--rerun", "--timeout", "20"]);

    expect(result.status).toBe(2);
    expect(parse(result)).toEqual(
      expect.objectContaining({
        status: "findings",
        coverage: "reviewed",
        receipt: expect.objectContaining({ reviewId: 5 }),
        check: { conclusion: "success", runUrl: "https://example/run/21", correlated: false, event: "issue_comment" },
      }),
    );
    expect(ghCalls().filter((call) => call.startsWith("pr comment"))).toEqual([
      "pr comment 7 --repo o/r --body /robin",
    ]);
  });

  it("never reports a pre-existing receipt as the result of its own /robin", () => {
    const stale = botReview({ id: 3, body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [0, 0, 0, 0])}` });
    withFixture({
      reviews: [stale],
      runsSteps: [[], [commentRun()], [commentRun({ status: "completed", conclusion: "success" })]],
    });

    const result = pr(["--rerun", "--timeout", "20"]);

    expect(result.status).toBe(3);
    const body = parse(result);
    expect(body).toEqual(
      expect.objectContaining({
        status: "missing",
        coverage: "missing",
        receipt: null,
        check: { conclusion: "success", runUrl: "https://example/run/21", correlated: false, event: "issue_comment" },
      }),
    );
    expect(body.message).toContain("without posting a review");
  });

  it("reports missing when the dispatched workflow never starts", () => {
    withFixture({ runs: [] });

    const result = pr(["--rerun", "--timeout", "0.4"]);

    expect(result.status).toBe(3);
    const body = parse(result);
    expect(body.status).toBe("missing");
    expect(body.message).toContain("did not start");
    expect(body.message).not.toContain("synchronize");
  });

  it("reports outdated when the head moves while waiting for an active run", () => {
    withFixture({
      headSteps: [NEW_HEAD],
      runsSteps: [[prRun({ status: "in_progress", conclusion: null })], [prRun({ conclusion: "success" })]],
      reviews: [],
    });

    const result = pr(["--timeout", "20"]);

    expect(result.status).toBe(3);
    expect(parse(result)).toEqual(
      expect.objectContaining({ status: "outdated", coverage: "outdated", head: NEW_HEAD }),
    );
  });

  it("reports running when a correlated run is still active at the timeout", () => {
    withFixture({ runs: [prRun({ status: "queued", conclusion: null })] });

    const result = pr(["--timeout", "0.3"]);

    expect(result.status).toBe(3);
    const body = parse(result);
    expect(body).toEqual(
      expect.objectContaining({ status: "running", coverage: "running", check: expect.objectContaining({ correlated: true }) }),
    );
    expect(body.message).toContain("still running on");
  });

  it("says so honestly when only an uncorrelated comment run is active at the timeout", () => {
    withFixture({ runs: [commentRun()] });

    const result = pr(["--timeout", "0.3"]);

    expect(result.status).toBe(3);
    const body = parse(result);
    expect(body).toEqual(
      expect.objectContaining({
        status: "running",
        check: { conclusion: null, runUrl: "https://example/run/21", correlated: false, event: "issue_comment" },
      }),
    );
    expect(body.message).toContain("the API does not tie it to a pull request");
  });

  it("is not blocked by a run the API pins to another pull request", () => {
    withFixture({
      runs: [
        prRun({ id: 8, head_sha: OLD_HEAD, status: "in_progress", conclusion: null, pull_requests: [{ number: 99, head: { sha: OLD_HEAD } }] }),
      ],
      reviews: [botReview({ body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [0, 0, 0, 0])}` })],
    });

    const result = pr(["--timeout", "20"]);

    expect(result.status).toBe(0);
    expect(parse(result)).toEqual(expect.objectContaining({ status: "clean", check: null }));
  });

  it("waits for this PR's run that started at an older commit without claiming it covers the head", () => {
    withFixture({
      runs: [
        prRun({
          id: 7,
          head_sha: OLD_HEAD,
          status: "in_progress",
          conclusion: null,
          pull_requests: [{ number: 7, head: { sha: OLD_HEAD } }],
        }),
      ],
    });

    const result = pr(["--rerun", "--timeout", "0.4"]);

    expect(result.status).toBe(3);
    const body = parse(result);
    expect(body).toEqual(
      expect.objectContaining({
        status: "running",
        coverage: "running",
        check: expect.objectContaining({ correlated: false, event: "pull_request" }),
      }),
    );
    expect(body.message).toContain("started at an older commit");
    expect(ghCalls().some((call) => call.startsWith("pr comment"))).toBe(false);
  });

  it("trusts explicit PR identity over a shared head SHA", () => {
    withFixture({
      runs: [
        prRun({ id: 8, status: "in_progress", conclusion: null, pull_requests: [{ number: 99, head: { sha: HEAD } }] }),
      ],
      reviews: [botReview({ body: `## ${SIGNATURE}\n${marker("reviewed", HEAD, [0, 0, 0, 0])}` })],
    });

    const result = pr(["--timeout", "20"]);

    expect(result.status).toBe(0);
    expect(parse(result)).toEqual(expect.objectContaining({ status: "clean", check: null }));
  });
});

// --------------------------------------------------------------------------
// `robin-review pr --local`
// --------------------------------------------------------------------------

const FAKE_ENGINE = `
const fs = require("fs");
process.stdout.write("fake engine stdout\\n");
process.stderr.write("fake engine stderr\\n");
const inputs = {};
for (const [key, value] of Object.entries(process.env)) {
  if (key.startsWith("INPUT_") || key.startsWith("GITHUB_") || key.startsWith("RUNNER_") || key.startsWith("ACTIONS_") || key === "CI" || key === "ROBIN_AGENT_CALLER" || key === "ROBIN_POISON") {
    inputs[key] = key === "INPUT_GITHUB-TOKEN" ? "<present:" + String(value).length + ">" : value;
  }
}
fs.writeFileSync(process.env.FAKE_ENGINE_DUMP, JSON.stringify({ inputs, cwd: process.cwd() }));
const plan = JSON.parse(process.env.FAKE_ENGINE_PLAN || "{}");
if (plan.exitCode) process.exit(plan.exitCode);
const lines = Object.entries(plan.outputs || {}).map(([key, value]) => key + "<<EOF\\n" + value + "\\nEOF");
fs.appendFileSync(process.env.GITHUB_OUTPUT, lines.join("\\n") + "\\n");
`;

describe("robin-review pr --local", () => {
  let dir: string;
  let workspace: string;
  let enginePath: string;
  let dumpPath: string;
  let logPath: string;
  let fixturePath: string;
  let env: NodeJS.ProcessEnv;
  let head: string;
  let baseSha: string;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "robin-local-"));
    const binDir = path.join(dir, "bin");
    fs.mkdirSync(binDir);
    const fakeGh = path.join(binDir, "gh");
    fs.writeFileSync(fakeGh, FAKE_GH);
    fs.chmodSync(fakeGh, 0o755);

    workspace = path.join(dir, "workspace");
    fs.mkdirSync(workspace);
    const git = (args: string[]) =>
      cp.execFileSync("git", ["-C", workspace, "-c", "user.email=t@example", "-c", "user.name=T", ...args], {
        encoding: "utf8",
      }).trim();
    git(["init", "-q"]);
    git(["commit", "-q", "--allow-empty", "-m", "base"]);
    baseSha = git(["rev-parse", "HEAD"]);
    git(["commit", "-q", "--allow-empty", "-m", "head"]);
    head = git(["rev-parse", "HEAD"]);

    enginePath = path.join(dir, "engine.js");
    fs.writeFileSync(enginePath, FAKE_ENGINE);
    dumpPath = path.join(dir, "engine-dump.json");
    logPath = path.join(dir, "gh.log");
    fs.writeFileSync(logPath, "");
    fixturePath = path.join(dir, "fixture.json");
    env = {
      ...process.env,
      PATH: `${binDir}:${process.env.PATH}`,
      FAKE_GH_LOG: logPath,
      FAKE_GH_FIXTURE: fixturePath,
      FAKE_ENGINE_DUMP: dumpPath,
      // Inherited Actions settings that the CLI must strip before spawning.
      INPUT_REQUEST_CHANGES: "true",
      "INPUT_REQUEST-CHANGES": "true",
      GITHUB_EVENT_NAME: "pull_request",
      RUNNER_TEMP: "/inherited/tmp",
      ACTIONS_RUNTIME_TOKEN: "inherited",
      CI: "true",
      ROBIN_POISON: "kept",
    };
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const writeFixture = (overrides: Partial<Fixture> = {}) => {
    fs.writeFileSync(
      fixturePath,
      JSON.stringify({
        pr: { number: 7, headRefOid: head, baseRefName: "main", baseRefOid: baseSha, url: "https://example/pr/7" },
        reviews: [],
        runs: [],
        workflows: [],
        contents: {},
        login: "octo-human",
        token: "fake-token-abcdefghijklmnop",
        ...overrides,
      }),
    );
  };

  const local = (args: string[] = [], plan: any = {}) =>
    cp.spawnSync(
      "node",
      [BIN, "pr", "7", "--repo", "o/r", "--json", "--local", "--workspace", workspace, "--engine", enginePath, ...args],
      { encoding: "utf8", env: { ...env, FAKE_ENGINE_PLAN: JSON.stringify(plan) } },
    );

  it("runs the shipped engine once at the exact head and returns its validated receipt", () => {
    const body = `## ${SIGNATURE}\n${marker("reviewed", head, [0, 0, 1, 0])}`;
    writeFixture({
      reviewsById: {
        "42": { id: 42, commit_id: head, state: "COMMENTED", body, html_url: "https://example/review/42", submitted_at: "2026-01-02T00:00:00Z", user: { login: "octo-human" } },
      },
    });

    const result = local([], { outputs: { outcome: "reviewed", "review-id": "42", head } });
    const dump = JSON.parse(fs.readFileSync(dumpPath, "utf8"));

    expect(result.status).toBe(2);
    const payload = JSON.parse(result.stdout);
    expect(payload).toEqual(
      expect.objectContaining({
        status: "findings",
        coverage: "reviewed",
        execution: "local",
        findings: { high: 0, medium: 0, low: 1, suggestions: 0 },
        engine: expect.objectContaining({ path: enginePath, model: "luna-5-6-low-subscription", caller: expect.stringMatching(/^(codex|claude)$/) }),
      }),
    );
    expect(payload.engine.sha256).toMatch(/^[0-9a-f]{64}$/);

    // Forced policy, and nothing inherited from the surrounding Actions-like env.
    expect(dump.inputs["INPUT_REQUEST-CHANGES"]).toBe("false");
    expect(dump.inputs["INPUT_LLM-BASE-URL"]).toBe("rolly-agent");
    expect(dump.inputs["INPUT_EXPECTED-HEAD-SHA"]).toBe(head);
    expect(dump.inputs["INPUT_PR-NUMBER"]).toBe("7");
    expect(dump.inputs["INPUT_REVIEW-ON-SYNCHRONIZE"]).toBe("false");
    expect(dump.inputs["INPUT_FAIL-ON-HIGH"]).toBe("false");
    expect(dump.inputs.GITHUB_EVENT_NAME).toBe("workflow_dispatch");
    expect(dump.inputs.GITHUB_REPOSITORY).toBe("o/r");
    expect(dump.inputs.GITHUB_WORKSPACE).toBe(workspace);
    expect(dump.inputs["INPUT_GITHUB-TOKEN"]).toMatch(/^<present:\d+>$/);
    expect(dump.inputs.RUNNER_TEMP).not.toBe("/inherited/tmp");
    expect(dump.inputs.CI).toBeUndefined();
    expect(dump.inputs.ACTIONS_RUNTIME_TOKEN).toBeUndefined();
    expect(dump.inputs.ROBIN_POISON).toBe("kept");

    // The token never reaches any output stream.
    expect(result.stdout).not.toContain("fake-token-abcdefghijklmnop");
    expect(result.stderr).not.toContain("fake-token-abcdefghijklmnop");
    expect(result.stdout.trim().split("\n")).toHaveLength(1);
    expect(result.stderr).toContain("fake engine stdout");

    // The temp dir the engine wrote into is gone.
    expect(fs.existsSync(dump.inputs.RUNNER_TEMP)).toBe(false);
  });

  it("reports incomplete when the engine's reported review does not validate", () => {
    writeFixture({
      reviewsById: {
        "42": { id: 42, commit_id: OLD_HEAD, state: "COMMENTED", body: `${marker("reviewed", OLD_HEAD, [0, 0, 0, 0])}`, user: { login: "octo-human" } },
      },
    });

    const result = local([], { outputs: { outcome: "reviewed", "review-id": "42" } });

    expect(result.status).toBe(3);
    expect(JSON.parse(result.stdout)).toEqual(
      expect.objectContaining({ status: "incomplete", coverage: "incomplete", execution: "local", findings: null }),
    );
  });

  it("reports incomplete when the engine exits non-zero", () => {
    writeFixture();

    const result = local([], { exitCode: 3 });

    expect(result.status).toBe(3);
    expect(JSON.parse(result.stdout).coverage).toBe("incomplete");
  });

  it("reports outdated when the head moves during the local run", () => {
    const body = `## ${SIGNATURE}\n${marker("reviewed", head, [0, 0, 0, 0])}`;
    writeFixture({
      headSteps: [NEW_HEAD],
      reviewsById: {
        "42": { id: 42, commit_id: head, state: "COMMENTED", body, user: { login: "octo-human" } },
      },
    });

    const result = local([], { outputs: { outcome: "reviewed", "review-id": "42" } });

    expect(result.status).toBe(3);
    expect(JSON.parse(result.stdout)).toEqual(
      expect.objectContaining({ status: "outdated", coverage: "outdated", head: NEW_HEAD }),
    );
  });

  it("refuses to run when the workspace is not checked out at the PR head", () => {
    writeFixture({
      pr: { number: 7, headRefOid: HEAD, baseRefName: "main", baseRefOid: baseSha, url: "https://example/pr/7" },
    });

    const result = local();

    expect(result.status).toBe(1);
    expect(JSON.parse(result.stdout)).toEqual(
      expect.objectContaining({ status: "error", message: expect.stringContaining("not the PR head") }),
    );
    expect(fs.existsSync(dumpPath)).toBe(false);
  });

  it("refuses a non-subscription model and never spawns the engine", () => {
    writeFixture();

    const result = local(["--model", "luna-5-6-low-api"]);

    expect(result.status).toBe(1);
    expect(JSON.parse(result.stdout).message).toContain("-subscription");
    expect(fs.existsSync(dumpPath)).toBe(false);
  });

  it("does not execute while a Robin workflow run is active on the head", () => {
    writeFixture({
      workflows: [{ id: WORKFLOW_ID, path: ROBIN_PATH, state: "active" }],
      contents: { [ROBIN_PATH]: ROBIN_WORKFLOW },
      runs: [prRun({ head_sha: head, status: "in_progress", conclusion: null, pull_requests: [{ number: 7, head: { sha: head } }] })],
    });

    const result = local();

    expect(result.status).toBe(3);
    const body = JSON.parse(result.stdout);
    expect(body.coverage).toBe("running");
    expect(body.check.correlated).toBe(true);
    expect(fs.existsSync(dumpPath)).toBe(false);
  });

  it("does not execute while a comment-triggered run the API cannot place is active", () => {
    writeFixture({
      workflows: [{ id: WORKFLOW_ID, path: ROBIN_PATH, state: "active" }],
      contents: { [ROBIN_PATH]: ROBIN_WORKFLOW },
      runs: [commentRun()],
    });

    const result = local();

    expect(result.status).toBe(3);
    const body = JSON.parse(result.stdout);
    expect(body.coverage).toBe("running");
    expect(body.check).toEqual({ conclusion: null, runUrl: "https://example/run/21", correlated: false, event: "issue_comment" });
    expect(body.message).toContain("the API does not tie it to a pull request");
    expect(fs.existsSync(dumpPath)).toBe(false);
  });

  it("returns an existing complete receipt instead of running again", () => {
    writeFixture({
      reviews: [
        {
          id: 12,
          commit_id: head,
          state: "COMMENTED",
          body: `## ${SIGNATURE}\n${marker("reviewed", head, [0, 0, 0, 0])}`,
          submitted_at: "2026-01-01T00:00:00Z",
          html_url: "https://example/review/12",
          user: { login: "github-actions[bot]" },
        },
      ],
    });

    const result = local();

    expect(result.status).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual(
      expect.objectContaining({ status: "clean", coverage: "reviewed", execution: "actions" }),
    );
    expect(fs.existsSync(dumpPath)).toBe(false);
  });

  it("fails when the engine bundle is missing rather than resolving one from the workspace", () => {
    writeFixture();

    const result = cp.spawnSync(
      "node",
      [BIN, "pr", "7", "--repo", "o/r", "--json", "--local", "--workspace", workspace, "--engine", path.join(dir, "absent.js")],
      { encoding: "utf8", env },
    );

    expect(result.status).toBe(1);
    expect(JSON.parse(result.stdout).message).toContain("engine not found");
  });
});
