import * as cp from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

const BIN = path.resolve(__dirname, "..", "bin", "robin-review.js");
const TEMPLATE = path.resolve(__dirname, "..", "templates", "robin.yml");

describe("robin-review CLI", () => {
  let dir: string;

  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "robin-bin-"));
    cp.execSync("git init -q", { cwd: dir });
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const run = (env: Record<string, string> = {}) =>
    cp.execSync(`node "${BIN}"`, {
      stdio: "pipe",
      cwd: dir,
      env: { ...process.env, ROBIN_SKILL: "0", ...env },
    }).toString();

  it("creates the canonical workflow with the given ref", () => {
    run({ ROBIN_REF: "v2" });

    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    const workflow = fs.readFileSync(workflowPath, "utf8");
    const expected = fs.readFileSync(TEMPLATE, "utf8").replace("review.yml@main", "review.yml@v2");
    expect(workflow).toBe(expected);
    expect(workflow).toContain("Generated by robin-review");
    expect(workflow).toContain("uses: antongulin/robin/.github/workflows/review.yml@v2");
    expect(workflow).toContain("LLM_API_KEY: ${{ secrets.LLM_API_KEY }}");
  });

  it("is idempotent and keeps an existing modern ref", () => {
    run({ ROBIN_REF: "v1" });
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    const before = fs.readFileSync(workflowPath, "utf8");

    const output = run();

    expect(output).toContain("is already current");
    expect(fs.readFileSync(workflowPath, "utf8")).toBe(before);
    expect(fs.existsSync(path.join(dir, ".github", "robin-workflow-archive"))).toBe(false);
  });

  it("archives historical workflow names and variants before creating the canonical file", () => {
    const workflows = path.join(dir, ".github", "workflows");
    fs.mkdirSync(workflows, { recursive: true });
    fs.writeFileSync(
      path.join(workflows, "code-review.yml"),
      "name: Universal Code Reviewer\njobs:\n  review:\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\n",
    );
    fs.writeFileSync(
      path.join(workflows, "ai-review.yaml"),
      "name: Robin\njobs:\n  review:\n    steps:\n      - uses: antongulin/robin@main\n",
    );
    fs.writeFileSync(
      path.join(workflows, "legacy-action.yml"),
      "name: Code Review\njobs:\n  review:\n    steps:\n      - uses: antongulin/universal-code-reviewer@main\n",
    );

    const output = run();
    const archive = path.join(dir, ".github", "robin-workflow-archive");
    const canonical = fs.readFileSync(path.join(workflows, "robin.yml"), "utf8");

    expect(output).toContain("Multiple Robin workflows found; using default ref (main)");
    expect(output).toContain("Archived .github/workflows/code-review.yml");
    expect(output).toContain("Archived .github/workflows/ai-review.yaml");
    expect(output).toContain("Archived .github/workflows/legacy-action.yml");
    expect(fs.existsSync(path.join(workflows, "code-review.yml"))).toBe(false);
    expect(fs.existsSync(path.join(workflows, "ai-review.yaml"))).toBe(false);
    expect(fs.existsSync(path.join(workflows, "legacy-action.yml"))).toBe(false);
    expect(fs.existsSync(path.join(archive, "code-review.yml.disabled"))).toBe(true);
    expect(fs.existsSync(path.join(archive, "ai-review.yaml.disabled"))).toBe(true);
    expect(fs.existsSync(path.join(archive, "legacy-action.yml.disabled"))).toBe(true);
    expect(canonical).toContain("antongulin/robin/.github/workflows/review.yml@main");

    fs.copyFileSync(
      path.join(archive, "code-review.yml.disabled"),
      path.join(workflows, "code-review.yml"),
    );
    const duplicateOutput = run();
    expect(duplicateOutput).toContain(
      "Removed .github/workflows/code-review.yml (identical copy already at .github/robin-workflow-archive/code-review.yml.disabled)",
    );
  });

  it("archives an older canonical workflow while preserving its modern ref", () => {
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
    fs.writeFileSync(
      workflowPath,
      "name: Robin\njobs:\n  review:\n    uses: antongulin/robin/.github/workflows/review.yml@v1\n",
    );

    run();

    expect(fs.readFileSync(workflowPath, "utf8")).toContain("review.yml@v1");
    expect(
      fs.existsSync(path.join(dir, ".github", "robin-workflow-archive", "robin.yml.disabled")),
    ).toBe(true);
  });

  it("uses a numbered archive when the first destination has different content", () => {
    const workflows = path.join(dir, ".github", "workflows");
    const archive = path.join(dir, ".github", "robin-workflow-archive");
    fs.mkdirSync(workflows, { recursive: true });
    fs.mkdirSync(archive, { recursive: true });
    const legacy =
      "name: Universal Code Reviewer\njobs:\n  review:\n    uses: antongulin/universal-code-reviewer/.github/workflows/review.yml@v0\n";
    fs.writeFileSync(path.join(workflows, "code-review.yml"), legacy);
    fs.writeFileSync(path.join(archive, "code-review.yml.disabled"), "different archive\n");

    run();

    expect(fs.readFileSync(path.join(archive, "code-review.yml.1.disabled"), "utf8")).toBe(
      legacy,
    );
  });

  it("refuses to overwrite an unrelated canonical workflow", () => {
    const workflowPath = path.join(dir, ".github", "workflows", "robin.yml");
    fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
    fs.writeFileSync(workflowPath, "name: Unrelated automation\n");

    expect(() => run()).toThrow();
    expect(fs.readFileSync(workflowPath, "utf8")).toBe("name: Unrelated automation\n");
  });

  it("does not add a consumer workflow to Robin's source repository", () => {
    fs.writeFileSync(path.join(dir, "package.json"), '{"name":"robin-review"}\n');
    fs.writeFileSync(path.join(dir, "action.yml"), "name: Robin\n");
    fs.mkdirSync(path.join(dir, "skills", "robin"), { recursive: true });
    fs.writeFileSync(path.join(dir, "skills", "robin", "SKILL.md"), "# Robin\n");
    fs.mkdirSync(path.join(dir, ".github", "workflows"), { recursive: true });
    fs.writeFileSync(path.join(dir, ".github", "workflows", "self-test.yml"), "name: Self-Test\n");

    const output = run();

    expect(output).toContain("Robin source repository detected");
    expect(fs.existsSync(path.join(dir, ".github", "workflows", "robin.yml"))).toBe(false);
  });

  it("rejects a ROBIN_REF with YAML metacharacters", () => {
    expect(() => run({ ROBIN_REF: "main\njobs: {}" })).toThrow();
    expect(fs.existsSync(path.join(dir, ".github", "workflows", "robin.yml"))).toBe(false);
  });

  it("fails outside a git repository", () => {
    const bare = fs.mkdtempSync(path.join(os.tmpdir(), "robin-nogit-"));
    try {
      expect(() =>
        cp.execSync(`node "${BIN}"`, {
          cwd: bare,
          env: { ...process.env, ROBIN_SKILL: "0" },
          stdio: "pipe",
        })
      ).toThrow();
    } finally {
      fs.rmSync(bare, { recursive: true, force: true });
    }
  });

  it("is tracked as an executable npm binary", () => {
    expect(fs.statSync(BIN).mode & 0o111).not.toBe(0);
  });

  it("exposes exact-head PR review control", () => {
    const output = cp.execFileSync("node", [BIN, "pr", "--help"], { encoding: "utf8" });
    expect(output).toContain("robin-review pr [number|url]");
    expect(output).toContain("--rerun");
    expect(output).toContain("--json");
  });

  it("returns clean only for a successful exact-head approval", () => {
    const fakeBin = path.join(dir, "bin");
    const fakeGh = path.join(fakeBin, "gh");
    fs.mkdirSync(fakeBin);
    fs.writeFileSync(fakeGh, `#!/bin/sh
case "$1 $2" in
  "pr view") echo '{"number":7,"headRefOid":"abc123","url":"https://example/pr/7"}' ;;
  "api repos/o/r/commits/abc123/check-runs?check_name=review&per_page=100") echo '{"check_runs":[{"id":9,"name":"review","status":"completed","conclusion":"success","started_at":"2026-01-01T00:00:00Z","html_url":"https://example/run/9","app":{"slug":"github-actions"}}]}' ;;
  "api --paginate") printf '[[{"commit_id":"abc123","state":"%s","body":"## :bow_and_arrow: Robin","submitted_at":"2026-01-01T00:01:00Z","html_url":"https://example/review/1","user":{"login":"github-actions[bot]"}}]]\n' "$FAKE_VERDICT" ;;
  *) echo "unexpected gh args: $*" >&2; exit 1 ;;
esac
`);
    fs.chmodSync(fakeGh, 0o755);
    const env = { ...process.env, PATH: `${fakeBin}:${process.env.PATH}` };
    const cleanRun = cp.spawnSync("node", [BIN, "pr", "7", "--repo", "o/r", "--json"], {
      encoding: "utf8",
      env: { ...env, FAKE_VERDICT: "APPROVED" },
    });
    expect({ status: cleanRun.status, stderr: cleanRun.stderr, stdout: cleanRun.stdout }).toEqual({
      status: 0,
      stderr: "",
      stdout: cleanRun.stdout,
    });
    expect(JSON.parse(cleanRun.stdout)).toEqual(expect.objectContaining({ status: "clean", head: "abc123", verdict: "APPROVED" }));

    try {
      cp.execFileSync("node", [BIN, "pr", "7", "--repo", "o/r", "--json"], {
        encoding: "utf8",
        env: { ...env, FAKE_VERDICT: "CHANGES_REQUESTED" },
      });
      throw new Error("expected blocked exit");
    } catch (error: any) {
      expect(error.status).toBe(2);
      expect(JSON.parse(error.stdout)).toEqual(expect.objectContaining({ status: "blocked", verdict: "CHANGES_REQUESTED" }));
    }
  });

  it("reruns through the PR command and waits for a new exact-head check", () => {
    const fakeBin = path.join(dir, "bin");
    const fakeGh = path.join(fakeBin, "gh");
    const marker = path.join(dir, "rerun-requested");
    fs.mkdirSync(fakeBin);
    fs.writeFileSync(fakeGh, `#!/bin/sh
case "$1 $2" in
  "pr view") echo '{"number":7,"headRefOid":"abc123","url":"https://example/pr/7"}' ;;
  "pr comment") printf '%s\n' "$*" > "$FAKE_MARKER" ;;
  "api repos/o/r/commits/abc123/check-runs?check_name=review&per_page=100") echo '{"check_runs":[]}' ;;
  "api --paginate")
    if [ -f "$FAKE_MARKER" ]; then id=2; submitted=2026-01-02; else id=1; submitted=2026-01-01; fi
    printf '[[{"id":%s,"commit_id":"abc123","state":"APPROVED","body":"## :bow_and_arrow: Robin","submitted_at":"%sT00:01:00Z","html_url":"https://example/review/%s","user":{"login":"github-actions[bot]"}}]]\n' "$id" "$submitted" "$id" ;;
  *) echo "unexpected gh args: $*" >&2; exit 1 ;;
esac
`);
    fs.chmodSync(fakeGh, 0o755);

    const result = cp.spawnSync("node", [BIN, "pr", "7", "--repo", "o/r", "--rerun", "--json"], {
      encoding: "utf8",
      env: { ...process.env, PATH: `${fakeBin}:${process.env.PATH}`, FAKE_MARKER: marker },
    });

    expect({ status: result.status, stdout: result.stdout, stderr: result.stderr }).toEqual({
      status: 0,
      stdout: result.stdout,
      stderr: "",
    });
    expect(fs.existsSync(marker)).toBe(true);
    expect(fs.readFileSync(marker, "utf8")).toBe("pr comment 7 --repo o/r --body /robin\n");
    expect(JSON.parse(result.stdout)).toEqual(expect.objectContaining({ status: "clean", check: "review", runUrl: "https://example/review/2" }));
  });
});
